### ISSUE TITLE
Color states for focus / hover

### ISSUE THREAD

**Issue by bryanjonker-illinois** [web-illinois/ilw-section-nav#2]
![Section Navigation](https://github.com/user-attachments/assets/e8e95dc6-f34c-4a74-8a48-986365ab0652)

Please change the states to match Courtney's document. 

For focus, you can add the following CSS which will reference the variables set in the ilw-global.css document (we are using "outline" instead of any explicit borders)

```
{
    background-color: var(--ilw-link--focus-background-color);
    color: var(--ilw-link--focus-color);
    outline: var(--ilw-link--focus-outline);
}
```

Variables are:
```
--ilw-link--focus-background-color:var(--il-industrial-lighter-4);
--ilw-link--focus-color:var(--il-blue);
--ilw-link--focus-outline:solid var(--il-blue) 1px;
```

**Comment by marvel-uiuc** [comment]
Closed in e3295f440afea875f8ed0f5994ecd7235f97a06d.
