### ISSUE TITLE
font isn't being loaded for menu

### ISSUE THREAD

**Issue by nhjohnstone** [web-illinois/ilw-section-nav#6]
Testing this out in the drupal theme, and the font for the menu isn't being loaded.
I am seeing this on the component demo page as well.

I think something like this needs to be added
--ilw-section-nav--font-family:  var(--il-font-sans);

<img width="1197" alt="Screenshot 2024-09-27 at 2 20 50 PM" src="https://github.com/user-attachments/assets/c0b02948-80c6-477f-9184-d8da77e54873">

**Comment by marvel-uiuc** [comment]
It is currently inheriting its parent's font, it seems like the sidebars tend to fall outside of the themed content, so it's not getting the appropriate font. I'll add a variable to set the font to fix this.

**Comment by marvel-uiuc** [comment]
This should be resolved in #7 and will be included in the next Toolkit release.

**Comment by marvel-uiuc** [comment]
This has been included in the toolkit release, so I'm closing it. @nhjohnstone reopen if you still see an issue.
